LATENT_DIM = 128
NOISE = 0.15
NUMBER_OF_IMAGES = 3
NUMBER_OF_EPOCHS = 200

# WARPGAN
WIDTH = 512
HEIGHT = 512
CHANNELS = 3
BATCH_SIZE = 10
NUMBER_OF_LANDMARKS = 16
BOTTLENECK_SIZE = 512
NUMBER_OF_CLASSES = 1000 # TODO uzupełnić

# COMPOSED
INPUT_SHAPE = (BATCH_SIZE, WIDTH, HEIGHT, CHANNELS)
